import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const satoshi = localFont({
  variable: "--font-satoshi",
  src: [
    {
      path: "./fonts/satoshi/Satoshi-Regular.woff2",
      weight: "400",
      style: "regular",
    },
    {
      path: "./fonts/satoshi/Satoshi-Bold.woff2",
      weight: "700",
      style: "bold",
    },
  ],
});

const degular = localFont({
  variable: "--font-degular",
  src: [
    {
      path: "./fonts/degualar/Degular-Thin.otf",
      weight: "100",
      style: "thin",
    },
    {
      path: "./fonts/degualar/Degular-Light.otf",
      weight: "300",
      style: "light",
    },
    {
      path: "./fonts/degualar/Degular-Regular.otf",
      weight: "400",
      style: "regular",
    },
    {
      path: "./fonts/degualar/Degular-Medium.otf",
      weight: "500",
      style: "medium",
    },
    {
      path: "./fonts/degualar/Degular-Semibold.otf",
      weight: "600",
      style: "semibold",
    },
    {
      path: "./fonts/degualar/Degular-Bold.otf",
      weight: "700",
      style: "bold",
    },
  ],
});

const panchang = localFont({
  variable: "--font-panchang",
  src: [
    {
      path: "./fonts/panchang/Panchang-Regular.otf",
      weight: "400",
      style: "regular",
    },
  ],
});

const metropolis = localFont({
  variable: "--font-metropolis",
  src: [
    {
      path: "./fonts/metropolis/Metropolis-Thin.woff2",
      weight: "100",
      style: "thin",
    },
    {
      path: "./fonts/metropolis/Metropolis-Light.woff2",
      weight: "300",
      style: "light",
    },
    {
      path: "./fonts/metropolis/Metropolis-Regular.woff2",
      weight: "400",
      style: "regular",
    },
    {
      path: "./fonts/metropolis/Metropolis-Medium.woff2",
      weight: "500",
      style: "medium",
    },
    {
      path: "./fonts/metropolis/Metropolis-SemiBold.woff2",
      weight: "600",
      style: "semibold",
    },
    {
      path: "./fonts/metropolis/Metropolis-Bold.woff2",
      weight: "700",
      style: "bold",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${metropolis.variable} ${degular.variable} ${panchang.variable} ${satoshi.variable} antialiased`}
      >
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
